PRODUCT_VERSION_MAJOR = 2
PRODUCT_VERSION_MINOR = 0

# versioning
EUCLID_CODENAME := Vertex
EUCLID_BUILD_TYPE ?= UNOFFICIAL
EUCLID_VARIANT := $(EUCLID_ZIP_TYPE)
EUCLID_DATE_YEAR := $(shell date -u +%Y)
EUCLID_DATE_MONTH := $(shell date -u +%m)
EUCLID_DATE_DAY := $(shell date -u +%d)
EUCLID_DATE_HOUR := $(shell date -u +%H)
EUCLID_DATE_MINUTE := $(shell date -u +%M)
EUCLID_BUILD_DATE := $(EUCLID_DATE_YEAR)$(EUCLID_DATE_MONTH)$(EUCLID_DATE_DAY)-$(EUCLID_DATE_HOUR)$(EUCLID_DATE_MINUTE)

# Check Official
ifeq ($(EUCLID_BUILD_TYPE), OFFICIAL)
  LIST = $(shell cat vendor/euclid/euclid.devices)
    ifeq ($(filter $(EUCLID_BUILD), $(LIST)), $(EUCLID_BUILD))
      EUCLID_BUILD_TYPE := OFFICIAL
    else
      EUCLID_BUILD_TYPE := UNOFFICIAL
    endif
endif

EUCLID_VERSION_SUFFIX := $(EUCLID_BUILD_DATE)-$(EUCLID_BUILDTYPE)$(EUCLID_EXTRAVERSION)-$(EUCLID_BUILD)

# Internal version
EUCLID_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(EUCLID_VERSION_SUFFIX)

# Display version
EUCLID_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR)-$(EUCLID_VERSION_SUFFIX)

# Codename version
EUCLID_DISPLAY_VERSION_CODENAME := 14-Vertex

# Props
PRODUCT_PRODUCT_PROPERTIES += \
  ro.euclid.version=$(EUCLID_DISPLAY_VERSION_CODENAME) \
  ro.euclid.codename=$(EUCLID_CODENAME) \
  ro.euclid.build.date=$(EUCLID_BUILD_DATE) \
  ro.euclid.releasevarient=$(EUCLID_ZIP_TYPE) \
  ro.euclid.releasetype=$(EUCLID_BUILD_TYPE) \
  ro.euclid.build.version=$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR) \
